

INSERT INTO `comercio_contenido` 
(`id_comercio_contenido`, `id_comercio`, `id_idioma`, `tipo_contenido`, `contenido`) 
VALUES

(null, 81, 1, 'quienes_somos', '<div class="columnaLeft">\n                <p>Fund Grube es una de las principales cadenas de tiendas de Canarias especializada en la venta de distintos productos de lujo y estilo de vida: Perfumería, Cosmética, Maquillaje, Relojería, Gafas de Sol, Bisutería, Marroquinería, Calzado y Moda. \n</p>\n<br>\n<p>\nEl cliente es el centro de atención de una empresa con visión de servicio, calidad, e innovación, a través de una red de 19 puntos de venta distribuidas en zonas turísticas y locales de cuatro de las Islas Canarias: Gran Canaria, Tenerife, Lanzarote y Fuerteventura.\n</p>\n<br>\n<p>\n30 años de experiencia avalan a un equipo de más de 400 profesionales, volcados en la atención al cliente y en el constante interés por ofrecer un surtido y selección de productos adecuado a los gustos y las tendencias de cada temporada.\n</p>\n<br>\n</div>\n<div class="columnaRight">\n<p>\nComo enfoque prioritario, los hermanos Chhabria han basado el desarrollo de su actividad empresarial en su Visión de trasmitir a las personas que acuden a las tiendas Fund Grube, tanto residentes como visitantes, el entorno de bienestar necesario para sentirse bienvenido en sus tiendas. Y cuando requieren un servicio asistido, ofrecerles como clientes, la máxima calidad profesional y humana en los productos y servicios de asesoramiento y postventa.\n</p>\n<br>\n<p>\nPara ello, todos los profesionales que trabajan en la Organización conocen y trasmiten los valores corporativos de Fund Grube SL que definen el Código Ético de la Compañía:\n</p>\n<em><ul>\n<li>Respeto</li>\n<li>Honestidad</li>\n<li>Igualdad</li>\n<li>Servicio</li>\n<li>Calidad</li>\n<li>Trabajo en Equipo</li>\n<li>Transparencia</li>\n<li>Imagen</li>\n</ul>\n</em>\n<div class=clearAll></div>\n</div>'),

(null, 81, 1, 'oferta', '<p>Aproveche el  20% de descuento sobre el precio original en los productos de joyería y bisutería durante el martes 19 y el miércoles 20 de noviembre. Adelante sus compras navideñas y benefíciese de esta genial oferta.</p>'),

(null, 81, 1, 'foto', '<p><img src=''../../../contenido_proyectos/pacoche/_comercios/fundgrube_galeria_1.jpg'' /></p>\n<p><img src=''../../../contenido_proyectos/pacoche/_comercios/fundgrube_galeria_2.jpg'' /></p>\n<p><img src=''../../../contenido_proyectos/pacoche/_comercios/fundgrube_galeria_3.jpg'' /></p>\n<p><img src=''../../../contenido_proyectos/pacoche/_comercios/fundgrube_galeria_4.jpg'' /></p>'),

(null, 82, 1, 'quienes_somos', '\n<div class="columnaLeft">\n    <p>Un sitio mágico donde divertirse, soltar adrenalina y pasarlo bien. Las atracciones tienen unas normas básicas a la entrada de cada atracción. La altura mínima para subir a las atracciones es de 80 cm. Los niños menores de 3 años y que no lleguen a la estatura indicada tienen un ‘playground’ (zona de juegos) que pueden utilizar de forma segura.\n    </p>\n    <br>\n    <p>\n        <span class=''relevante''>23 atracciones para el ocio de grandes y pequeños:</span> Montaña rusa, barco pirata, tiovivo, cine 4D, cochitos de choque, los toros mecánicos, ponis, loro show, etc...\n\n    </p>\n    <br>\n    <p>\n        <span class=''relevante''>BOWLING</span> 16 pistas profesionales y el ambiente más auténtico.\n    </p>\n    <br>\n</div>\n<div class="columnaRight">\n    <p>\n        Martes Promociones 50% de descuento.<br>\n        Jueves Rock & Bowl, noche de música rock and roll 70´s, 80´s y 90´s.<br>\n        Viernes Música internacional, premios, retransmisión de vídeos musicales…<br>\n        Sábados Música house a partir de las 22:00h la mejor música dance.\n    </p>\n    <br>\n    <p>\n        <span class=''relevante''>RESTAURANTES</span>\n        Restaurante Roque Nublo - Restaurante chino Taiwan <br>\n        Bar Bowling - Manolo´s Bar.\n    </p>\n<br>\n    <p>\n        <span class=''relevante''>ARTESANÍA</span>\n        Especial martes día feria artesanía Holiday World.<br>\n        Espectáculo tradicional canario, música y folklore, artesanía, tapas desde 3€.\n\n    </p>\n</div>\n<div class=clearAll></div>'),

(null, 82, 1, 'foto', '<p><img src=''../../../contenido_proyectos/pacoche/_comercios/holydayworld_galeria_1.jpg'' /></p>\n<p><img src=''../../../contenido_proyectos/pacoche/_comercios/holydayworld_galeria_2.jpg'' /></p>\n<p><img src=''../../../contenido_proyectos/pacoche/_comercios/holydayworld_galeria_3.jpg'' /></p>\n<p><img src=''../../../contenido_proyectos/pacoche/_comercios/holydayworld_galeria_4.jpg'' /></p>\n<p><img src=''../../../contenido_proyectos/pacoche/_comercios/holydayworld_galeria_5.jpg'' /></p>'),

(null, 82, 1, 'oferta', '<p>\n    Sorteamos un fin de semana para dos personas en el Aparthotel Rubimar Lanzarote.\nPara participar pincha en “me gusta” en el perfil de facebook de Ticketmas.\n</p>'),

(null, 83, 1, 'quienes_somos', '\n<div class="columnaLeft">\n    <p><strong>PACHA GRAN CANARIA Playa del Inglés</strong>, al sur de la isla de Gran Canaria, inauguró en 1984 y desde entonces ha logrado colocarse entre los mejores clubes de todo el Archipiélago Canario. Cuenta con una sala principal de más de 1.000 metros cuadrados con cuatro barras y un servicio de guardarropa que dan cobertura a este espacio. Un magnífico escenario que ha dado cabida a innumerables y prestigiosos artistas nacionales e internacionales.\n    </p>\n    <br>\n</div>\n<div class="columnaRight">\n    <p>\n        <span class=''relevante''>ESPACIOS DISPONIBLES PARA:</span>\n        <em>\n            <ul>\n                <li>Conciertos.</li>\n                <li>Localizaciones para cine y publicidad</li>\n                <li>Showrooms</li>\n                <li>Desfiles de moda</li>\n                <li>Presentaciones de producto</li>\n                <li>Fiestas privadas</li>\n                <li>Reuniones de empresa y particulares</li>\n            </ul>\n        </em>\n    </p>\n    <br>\n</div>\n<div class=clearAll></div>\n<div>\n    <p>\n        <span class=''relevante''>NUESTROS SERVICIOS INCLUYEN:</span>\n        <em>\n            <ul>\n                <li>Alquiler del espacio en exclusiva. Diferentes áreas para personalizar al máximo el evento a tu medida.</li>\n                <li>Material tecnológico audiovisual de última generación</li>\n                <li>Zonas VIP totalmente privadas con personal exclusivo y servicio de Seguridad, Limpieza, Guardarropa, Fotógrafo y Video, Servicio de Azafatas</li>\n                <li>DJ</li>\n                <li>Contratación de artistas y animación</li>\n                <li>Gabinete de prensa</li>\n                <li>Diseño y producción de materiales de comunicación</li>\n            </ul>\n        </em>\n    </p>\n</div>'),
(null, 83, 1, 'foto', '<p><img src=''../../../contenido_proyectos/pacoche/_comercios/pacha_galeria_1.png'' /></p>\n<p><img src=''../../../contenido_proyectos/pacoche/_comercios/pacha_galeria_2.png'' /></p>\n<p><img src=''../../../contenido_proyectos/pacoche/_comercios/pacha_galeria_3.png'' /></p>'),

(null, 83, 1, 'oferta', '\n<p>\n¿Quieres que tus noches en PACHA GRAN CANARIA sean aún más especiales?. HummerLimoGranCanaria y PACHA Gran Canaria presentan su servicio VIP Limousina + Reservado para 8 personas con una oferta inigualable. En caso de ser más personas, no dudes en llamarnos y te propondremos varias soluciones.\n</p>\n<br>\n<p>\n    <span class=''relevante''>La oferta incluye:</span>\n<ul>\n    <li>Recogida y paseo de una hora en Limousina Hummer H2.</li>\n    <li>2 Botellas de Cava ó 1 Botella de Licor (a elegir entre ron, vodka, ginebra) con refrescos.</li>\n    <li>Entrada gratis a PACHA Gran Canaria.</li>\n    <li>Reservado en zona VIP PACHA Gran Canaria.</li>\n    <li>2 Botellas a elegir en Reservado o Zona VIP.</li>\n</ul>\n<br>\n<p>\n    ¡Todo Incluido, desde 420 €, así que no tienes excusa para darte un capricho con tus amig@s!\n</p>\n<br>\n<p>\n    Consultar fechas, disponibilidad y zona de recogida.\n</p>'),

(null, 81, 1, 'proximamente', '<p>\r\n<img src="../../../contenido_proyectos/pacoche/_comercios/fundgrube_proximamente.png"/></p>'),

(null, 82, 1, 'proximamente', '<p>\r\n<img src="../../../contenido_proyectos/pacoche/_comercios/holidayworld_proximamente.png"/></p>'),

(null, 83, 1, 'proximamente', '<p>\n<img src="../../../contenido_proyectos/pacoche/_comercios/pacha_proximamente.png"/>\n</p>'),

(null, 84, 1, 'quienes_somos', '<p>Si desea disfrutar de una cena especial  durante sus vacaciones, en un entorno natural, tranquilo y acogedor, al aire libre rodeado de palmeras, el Restaurante a la Carta Aloha 37 es la opción ideal. Ubicado en los jardines del hotel, el Restaurante Aloha 37 ofrece una cocina internacional, variada y tradicional, con una <strong>amplia carta de vinos y postres</strong>. </p>'),

(null, 84, 1, 'foto', '<p><img src="../../../contenido_proyectos/pacoche/_comercios/aloha_galeria_1.jpg"/></p>\n<p><img src="../../../contenido_proyectos/pacoche/_comercios/aloha_galeria_2.jpg"/></p>\n<p><img src="../../../contenido_proyectos/pacoche/_comercios/aloha_galeria_3.jpg"/></p>\n<p><img src="../../../contenido_proyectos/pacoche/_comercios/aloha_galeria_4.jpg"/></p>'),

(null, 84, 1, 'proximamente', '<p><img src=''../../../contenido_proyectos/pacoche/_comercios/aloha_proximamente.png"/></p>'),

(null, 84, 1, 'video', '<p><img src=../../../contenido_proyectos/pacoche/_comercios/aloha_carta_1.jpg /></p>'), 





;
